let pattern =  '* * * * * * * * * * \n'
   pattern +=  '**                 * \n'
   pattern +=  '* *                 * \n'
   pattern +=  '*  *                 * \n'
   pattern +=  '*   *                 * \n'
   pattern +=  '*    *                 * \n'
   pattern +=  '*     *                 * \n'
   pattern +=  '*      *                 * \n'
   pattern +=  '*       *                 * \n'
   pattern +=  '*        * * * * * * * * * * \n'
   pattern +=  ' *       *                 * \n'
   pattern +=  '  *      *                 * \n'
   pattern +=  '   *     *                 * \n'
   pattern +=  '    *    *                 * \n'
   pattern +=  '     *   *                 * \n'
   pattern +=  '      *  *                 * \n'
   pattern +=  '       * *                 * \n'
   pattern +=  '        **                 * \n'
   pattern +=  '         * * * * * * * * * * '


exports.pattern = pattern;
